#
# Makefile
#

helloworld: helloworld.c
	gcc -ggdb -std=c99 -Wall -Werror -o helloworld helloworld.c -lncurses -lm

bold: bold.c
	gcc -ggdb -std=c99 -Wall -Werror -o bold bold.c -lncurses -lm

clean:
	rm -f *.o a.out core helloworld bold
